# Note: This workflow action is disabled, but kept here for reference. I am now using GitHub Actions to automatically build and push the Docker image to GitHub Container Registry, and then pull the latest image on the server and restart the container to deploy the latest changes. You can see the workflow file [here](../.github/workflows/docker_build_push.yml) and the deploy script [`deploy.sh`](../scripts/deploy.sh).

# The app is hosted on VPS server. So basically we SSH into it and run the deploy script (git pull etc.)
name: Deploy Production

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      # Login to Server via SSH and run deploy script to deploy
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.HOST_IP }}
          username: ${{ vars.HOST_USER }}
          key: ${{ secrets.MY_PRIVATE_KEY}}
          script: |
            #!/usr/bin/env bash
            set -e
            cd htdocs/baca.qurantajwid.my
            bash scripts/deploy.sh
